SEARCH_DIR("/usr/lib/x86_64-linux-gnu/")
SEARCH_DIR("/lib64/")
SEARCH_DIR("/lib/")
SEARCH_DIR("/usr/lib64/")
SEARCH_DIR("/usr/lib/")
SEARCH_DIR("/usr/lib/gcc/x86_64-linux-gnu/10/")
SEARCH_DIR("/lib/x86_64-linux-gnu/")
SEARCH_DIR("/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/")
SEARCH_DIR("/opt/lazarus/lazarus/components/datetimectrls/lib/x86_64-linux/qt5/")
SEARCH_DIR("/opt/lazarus/lazarus/lcl/units/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/lazarus/components/freetype/lib/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/lazarus/packager/units/x86_64-linux/")
SEARCH_DIR("./")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/httpd22/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/rtl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/tplylib/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/postgres/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/gtk2/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libmicrohttpd/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/zorba/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/rtl-generics/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/rtl-unicode/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/dblib/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/dbus/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/httpd24/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/opengles/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/rtl-objpas/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/pxlib/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/graph/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/rtl-extra/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/rsvg/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/numlib/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/openal/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fv/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/uuid/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libpng/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/imlib/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-sound/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-res/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/xforms/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-xml/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-stl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-extra/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/ldap/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/utmp/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libusb/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/regexpr/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-db/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-js/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/vcl-compat/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/jni/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/gtk1/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/mad/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-registry/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/dts/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/a52/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/gnome1/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/modplug/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-net/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/newt/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/users/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/gmp/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/ncurses/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/chm/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/mysql/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-passrc/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-web/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/ggi/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/cdrom/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/svgalib/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/opengl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libenet/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/opencl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fastcgi/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/googleapi/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/gdbm/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-async/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fppkg/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/symbolic/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/syslog/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/paszlib/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/ptc/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/odata/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/proj4/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/sqlite/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/openssl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/cairo/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/oggvorbis/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/gdbint/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fpmkunit/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libsee/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/zlib/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fpgtk/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/pastojs/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libcurl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libmagic/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libfontconfig/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/tcl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/webidl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fpindexer/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libvlc/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-fpcunit/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/unzip/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fftw/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/odbc/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/sdl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/oracle/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/pthreads/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libcups/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-process/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-base/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/ibase/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libgd/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libtar/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/bzip2/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/aspell/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/lua/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/imagemagick/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-json/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-sdo/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/x11/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/pcap/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-pdf/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/hermes/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-report/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-image/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/rtl-console/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/gnutls/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/hash/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libxml2/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libffi/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/iconvenc/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libgc/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/bfd/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/utils-pas2js/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/fpc/bin/x86_64-linux/")
INPUT(
/usr/lib/x86_64-linux-gnu/crti.o
/usr/lib/gcc/x86_64-linux-gnu/10/crtbeginS.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/si_c.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/abitag.o
/root/Documentos/opentef/publica/fontes/frente_caixa/lib/x86_64-linux/frente_caixa.o
/root/Documentos/opentef/publica/fontes/frente_caixa/lib/x86_64-linux/frente_caixa.or
/opt/lazarus/fpc/units/x86_64-linux/rtl/system.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/fpintres.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/objpas.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/cthreads.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/interfaces.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/forms.o
/opt/lazarus/lazarus/components/datetimectrls/lib/x86_64-linux/qt5/datetimectrls.o
/root/Documentos/opentef/publica/fontes/frente_caixa/lib/x86_64-linux/uprincipal.o
/root/Documentos/opentef/publica/fontes/frente_caixa/lib/x86_64-linux/umenuvenda.o
/root/Documentos/opentef/publica/fontes/frente_caixa/lib/x86_64-linux/def.o
/root/Documentos/opentef/publica/fontes/frente_caixa/lib/x86_64-linux/uimpressao.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/linux.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/baseunix.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/unix.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/unixtype.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/initc.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/dl.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/unixutil.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/ctypes.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/cwstring.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/interfacebase.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/dynlibs.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/unixcp.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/types.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/classes.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/sysutils.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/math.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpimage.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lclproc.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lcltype.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lmessages.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lclplatformdef.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/intfgraphics.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/themes.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazutf8.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/integerlist.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazutilities.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazloggerbase.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/graphtype.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/graphmath.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/errors.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/sysconst.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/typinfo.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/rtlconsts.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/laz_avl_tree.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazfileutils.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazmethodlist.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/laztracer.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lclstrconsts.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazutilsstrconsts.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/fpcadds.o
/opt/lazarus/fpc/units/x86_64-linux/rtl-objpas/strutils.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/gettext.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazclasses.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpreadbmp.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpwritebmp.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/bmpcomn.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpreadpng.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpwritepng.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpreadtiff.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpwritetiff.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fptiffcmn.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lclversion.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/icnstypes.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpimgcmn.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/pngcomn.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/zstream.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/zbase.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/gzio.o
/opt/lazarus/fpc/units/x86_64-linux/hash/crc.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/zdeflate.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/zinflate.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/trees.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/adler.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/infblock.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/infutil.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/infcodes.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/inftrees.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/inffast.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazversion.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/graphics.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lclintf.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/contnrs.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpcanvas.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpreadpnm.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpwritepnm.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpreadjpeg.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpwritejpeg.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpreadgif.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lresources.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lclrescache.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsreferences.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/clipping.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jpeglib.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdapimin.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdatasrc.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdapistd.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jmorecfg.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdeferr.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jinclude.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jerror.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jmemmgr.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdmarker.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdinput.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcomapi.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jutils.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jmemnobs.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdmaster.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdcolor.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdsample.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdpostct.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jddctmgr.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdphuff.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdhuff.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdcoefct.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdmainct.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jquant1.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jquant2.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdmerge.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdct.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jidctfst.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jidctint.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jidctflt.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jidctred.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcapistd.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcapimin.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdatadst.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcparam.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcinit.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcmarker.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcphuff.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jchuff.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcmaster.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jccolor.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcsample.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcprepct.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcdctmgr.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jccoefct.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcmainct.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jfdctint.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jfdctfst.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jfdctflt.o
/opt/lazarus/fpc/units/x86_64-linux/rtl-objpas/variants.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazconfigstorage.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/dynqueue.o
/opt/lazarus/fpc/units/x86_64-linux/rtl-objpas/varutils.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/avglvltree.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazdbglog.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/syncobjs.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/fileutil.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/utf8process.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazsysutils.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/maps.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/tmschema.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/fgl.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/masks.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-process/process.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-process/pipes.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/termio.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtint.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qt5.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lclmessageglue.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/controls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/extctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/dialogs.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/stdctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/graphutil.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazstringutils.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtx11dummywidget.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtproc.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lclclasses.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/messages.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/custapp.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/menus.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/customtimer.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/actnlist.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/clipbrd.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/helpintfs.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/imglist.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/uitypes.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/singleinstance.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wslclclasses.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpimgcanv.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fppixlcanv.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/pixtools.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/ellipses.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsimglist.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsproc.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsfactory.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/propertystorage.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/rttiutils.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsmenus.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazlogger.o
/opt/lazarus/fpc/units/x86_64-linux/chm/fasthtmlparser.o
/opt/lazarus/fpc/units/x86_64-linux/rtl-objpas/system.uitypes.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wscontrols.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsforms.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/popupnotifier.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/textstrings.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/extendedstrings.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsstdctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsextctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/buttons.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/buttonpanel.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lcltaskdialog.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/imagelistcache.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsbuttons.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsdialogs.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lazcanvas.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lazregions.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtobjects.o
/opt/lazarus/fpc/units/x86_64-linux/x11/x.o
/opt/lazarus/fpc/units/x86_64-linux/x11/xlib.o
/opt/lazarus/fpc/units/x86_64-linux/x11/xkb.o
/opt/lazarus/fpc/units/x86_64-linux/x11/xkblib.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtcaret.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtthemes.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsfactory.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwidgets.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtsystemtrayicon.o
/opt/lazarus/fpc/units/x86_64-linux/x11/xi.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/comctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/toolwin.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wscomctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wstoolwin.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtprivate.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/calendar.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/spin.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/grids.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/checklst.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/rubberband.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/pairsplitter.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wscalendar.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsspin.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-xml/htmldefs.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/maskedit.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/dynamicarray.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/laz2_xmlcfg.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lcsvutils.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazfilecache.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/laz2_dom.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/laz2_xmlread.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/laz2_xmlwrite.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/laz2_xmlutils.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/uriparser.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsgrids.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wschecklst.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsdesigner.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wspairsplitter.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsbuttons.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwscalendar.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwschecklst.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwscomctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwscontrols.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsdialogs.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsextctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsforms.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsmenus.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwspairsplitter.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsspin.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsstdctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsgrids.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsdesigner.o
/opt/lazarus/fpc/units/x86_64-linux/rtl-objpas/dateutils.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/extdlgs.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/calcform.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsextdlgs.o
/opt/lazarus/lazarus/components/datetimectrls/lib/x86_64-linux/qt5/datetimepicker.o
/opt/lazarus/lazarus/components/datetimectrls/lib/x86_64-linux/qt5/dbdatetimepicker.o
/opt/lazarus/lazarus/components/datetimectrls/lib/x86_64-linux/qt5/calcontrolwrapper.o
/opt/lazarus/lazarus/components/datetimectrls/lib/x86_64-linux/qt5/lclcalwrapper.o
/opt/lazarus/lazarus/packager/units/x86_64-linux/lazaruspackageintf.o
/opt/lazarus/fpc/units/x86_64-linux/rtl-extra/clocale.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-db/db.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/dbctrls.o
/opt/lazarus/fpc/units/x86_64-linux/rtl-objpas/fmtbcd.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/maskutils.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-db/dbconst.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/dbgrids.o
/opt/lazarus/fpc/units/x86_64-linux/hash/md5.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/base64.o
)
INPUT(
-lpthread
-ldl
-lQt5Pas
-lX11
)
GROUP(
-lgcc
-lgcc_eh
-lc
)
INPUT(
/usr/lib/gcc/x86_64-linux-gnu/10/crtendS.o
/usr/lib/x86_64-linux-gnu/crtn.o
)
SECTIONS
{
  .fpcdata           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
  .threadvar : { *(.threadvar .threadvar.* .gnu.linkonce.tv.*) }
}
INSERT AFTER .data;
