SEARCH_DIR("/usr/lib/x86_64-linux-gnu/")
SEARCH_DIR("/lib64/")
SEARCH_DIR("/lib/")
SEARCH_DIR("/usr/lib64/")
SEARCH_DIR("/usr/lib/")
SEARCH_DIR("/usr/lib/gcc/x86_64-linux-gnu/10/")
SEARCH_DIR("/lib/x86_64-linux-gnu/")
SEARCH_DIR("/root/Documentos/opentef/publica/fontes/libs/func/")
SEARCH_DIR("/opt/lazarus/lazarus/components/lazreport/source/addons/ZeosDB/lib/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/")
SEARCH_DIR("/opt/lazarus/config_lazarus/onlinepackagemanager/packages/ct4laz/pl_components/pl_lockbox/lib/x86_64-linux/qt5/")
SEARCH_DIR("/opt/lazarus/lazarus/components/lazreport/source/lib/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/lazarus/components/printers/lib/x86_64-linux/qt5/")
SEARCH_DIR("/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/")
SEARCH_DIR("/opt/lazarus/lazarus/components/synedit/units/x86_64-linux/qt5/")
SEARCH_DIR("/opt/lazarus/lazarus/components/lazcontrols/lib/x86_64-linux/qt5/")
SEARCH_DIR("/opt/lazarus/lazarus/components/cairocanvas/lib/x86_64-linux/qt5/")
SEARCH_DIR("/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/")
SEARCH_DIR("/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/lazarus/lcl/units/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxtools/x86_64-linux/qt5/")
SEARCH_DIR("/opt/lazarus/lazarus/components/freetype/lib/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/lazarus/components/buildintf/units/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/config_lazarus/onlinepackagemanager/packages/DCPcrypt/lib/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/lazarus/packager/units/x86_64-linux/")
SEARCH_DIR("./")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/httpd22/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/rtl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/tplylib/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/postgres/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/gtk2/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libmicrohttpd/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/zorba/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/rtl-generics/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/rtl-unicode/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/dblib/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/dbus/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/httpd24/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/opengles/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/rtl-objpas/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/pxlib/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/graph/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/rtl-extra/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/rsvg/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/numlib/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/openal/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fv/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/uuid/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libpng/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/imlib/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-sound/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-res/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/xforms/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-xml/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-stl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-extra/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/ldap/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/utmp/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libusb/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/regexpr/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-db/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-js/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/vcl-compat/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/jni/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/gtk1/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/mad/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-registry/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/dts/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/a52/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/gnome1/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/modplug/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-net/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/newt/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/users/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/gmp/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/ncurses/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/chm/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/mysql/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-passrc/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-web/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/ggi/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/cdrom/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/svgalib/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/opengl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libenet/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/opencl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fastcgi/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/googleapi/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/gdbm/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-async/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fppkg/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/symbolic/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/syslog/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/paszlib/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/ptc/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/odata/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/proj4/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/sqlite/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/openssl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/cairo/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/oggvorbis/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/gdbint/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fpmkunit/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libsee/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/zlib/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fpgtk/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/pastojs/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libcurl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libmagic/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libfontconfig/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/tcl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/webidl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fpindexer/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libvlc/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-fpcunit/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/unzip/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fftw/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/odbc/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/sdl/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/oracle/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/pthreads/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libcups/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-process/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-base/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/ibase/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libgd/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libtar/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/bzip2/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/aspell/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/lua/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/imagemagick/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-json/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-sdo/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/x11/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/pcap/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-pdf/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/hermes/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-report/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/fcl-image/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/rtl-console/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/gnutls/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/hash/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libxml2/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libffi/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/iconvenc/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/libgc/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/bfd/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/utils-pas2js/")
SEARCH_DIR("/opt/lazarus/fpc/units/x86_64-linux/")
SEARCH_DIR("/opt/lazarus/fpc/bin/x86_64-linux/")
VERSION
{
  {
    global:
      solicitacaoblocante;
      solicitacao;
      opentefstatus;
      desconectar;
      login;
      finalizar;
      inicializar;
    local:
      *;
  };
}
INPUT(
/usr/lib/x86_64-linux-gnu/crti.o
/usr/lib/gcc/x86_64-linux-gnu/10/crtbeginS.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/si_dll.o
/root/Documentos/opentef/publica/fontes/com_lib/lib/x86_64-linux/com_lib.o
/root/Documentos/opentef/publica/fontes/com_lib/lib/x86_64-linux/com_lib.or
/opt/lazarus/fpc/units/x86_64-linux/rtl/system.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/heaptrc.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/lnfodwrf.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/exeinfo.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/strings.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/fpintres.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/objpas.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/interfaces.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/classes.o
/root/Documentos/opentef/publica/fontes/com_lib/lib/x86_64-linux/com.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxnew.o
/root/Documentos/opentef/publica/fontes/com_lib/lib/x86_64-linux/funcoes.o
/root/Documentos/opentef/publica/fontes/com_lib/lib/x86_64-linux/comunicador.o
/root/Documentos/opentef/publica/fontes/com_lib/lib/x86_64-linux/def.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/cwstring.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/interfacebase.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/baseunix.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/ctypes.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/unix.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/unixtype.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/initc.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/dynlibs.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/unixcp.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/unixutil.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/dl.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/types.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/sysutils.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/math.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpimage.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lclproc.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lcltype.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lmessages.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lclplatformdef.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/intfgraphics.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/themes.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazutf8.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/integerlist.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazutilities.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazloggerbase.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/graphtype.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/graphmath.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/linux.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/errors.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/sysconst.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/typinfo.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/rtlconsts.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/laz_avl_tree.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazfileutils.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazmethodlist.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/laztracer.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lclstrconsts.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazutilsstrconsts.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/fpcadds.o
/opt/lazarus/fpc/units/x86_64-linux/rtl-objpas/strutils.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/gettext.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazclasses.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpreadbmp.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpwritebmp.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/bmpcomn.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpreadpng.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpwritepng.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpreadtiff.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpwritetiff.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fptiffcmn.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lclversion.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/icnstypes.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpimgcmn.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/pngcomn.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/zstream.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/zbase.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/gzio.o
/opt/lazarus/fpc/units/x86_64-linux/hash/crc.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/zdeflate.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/zinflate.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/trees.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/adler.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/infblock.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/infutil.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/infcodes.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/inftrees.o
/opt/lazarus/fpc/units/x86_64-linux/paszlib/inffast.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazversion.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/graphics.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lclintf.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/contnrs.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpcanvas.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpreadpnm.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpwritepnm.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpreadjpeg.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpwritejpeg.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpreadgif.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lresources.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lclrescache.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsreferences.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/clipping.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jpeglib.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdapimin.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdatasrc.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdapistd.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jmorecfg.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdeferr.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jinclude.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jerror.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jmemmgr.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdmarker.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdinput.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcomapi.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jutils.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jmemnobs.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdmaster.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdcolor.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdsample.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdpostct.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jddctmgr.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdphuff.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdhuff.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdcoefct.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdmainct.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jquant1.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jquant2.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdmerge.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdct.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jidctfst.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jidctint.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jidctflt.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jidctred.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcapistd.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcapimin.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jdatadst.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcparam.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcinit.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcmarker.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcphuff.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jchuff.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcmaster.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jccolor.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcsample.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcprepct.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcdctmgr.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jccoefct.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jcmainct.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jfdctint.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jfdctfst.o
/opt/lazarus/fpc/units/x86_64-linux/pasjpeg/jfdctflt.o
/opt/lazarus/fpc/units/x86_64-linux/rtl-objpas/variants.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazconfigstorage.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/dynqueue.o
/opt/lazarus/fpc/units/x86_64-linux/rtl-objpas/varutils.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/avglvltree.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazdbglog.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/syncobjs.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/fileutil.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/utf8process.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazsysutils.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/maps.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/tmschema.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/fgl.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/masks.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-process/process.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-process/pipes.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/termio.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtint.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/forms.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qt5.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lclmessageglue.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/controls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/extctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/dialogs.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/stdctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/graphutil.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazstringutils.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtx11dummywidget.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtproc.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lclclasses.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/messages.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/custapp.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/menus.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/customtimer.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/actnlist.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/clipbrd.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/helpintfs.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/imglist.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/uitypes.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/singleinstance.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wslclclasses.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fpimgcanv.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/fppixlcanv.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/pixtools.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-image/ellipses.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsimglist.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsproc.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsfactory.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/propertystorage.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/rttiutils.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsmenus.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazlogger.o
/opt/lazarus/fpc/units/x86_64-linux/chm/fasthtmlparser.o
/opt/lazarus/fpc/units/x86_64-linux/rtl-objpas/system.uitypes.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wscontrols.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsforms.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/popupnotifier.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/textstrings.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/extendedstrings.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsstdctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsextctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/buttons.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/buttonpanel.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lcltaskdialog.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/imagelistcache.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsbuttons.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsdialogs.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lazcanvas.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lazregions.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtobjects.o
/opt/lazarus/fpc/units/x86_64-linux/x11/x.o
/opt/lazarus/fpc/units/x86_64-linux/x11/xlib.o
/opt/lazarus/fpc/units/x86_64-linux/x11/xkb.o
/opt/lazarus/fpc/units/x86_64-linux/x11/xkblib.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtcaret.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtthemes.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsfactory.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwidgets.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtsystemtrayicon.o
/opt/lazarus/fpc/units/x86_64-linux/x11/xi.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/comctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/toolwin.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wscomctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wstoolwin.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtprivate.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/calendar.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/spin.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/grids.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/checklst.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/rubberband.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/pairsplitter.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wscalendar.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsspin.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-xml/htmldefs.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/maskedit.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/dynamicarray.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/laz2_xmlcfg.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lcsvutils.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lazfilecache.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/laz2_dom.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/laz2_xmlread.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/laz2_xmlwrite.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/laz2_xmlutils.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/uriparser.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsgrids.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wschecklst.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsdesigner.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wspairsplitter.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsbuttons.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwscalendar.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwschecklst.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwscomctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwscontrols.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsdialogs.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsextctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsforms.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsmenus.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwspairsplitter.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsspin.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsstdctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsgrids.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/qt5/qtwsdesigner.o
/opt/lazarus/fpc/units/x86_64-linux/rtl-objpas/dateutils.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/extdlgs.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/calcform.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsextdlgs.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/ct4laz/pl_components/pl_lockbox/lib/x86_64-linux/qt5/lbclass.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/ct4laz/pl_components/pl_lockbox/lib/x86_64-linux/qt5/lbrsa.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdTCPClient.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdTCPServer.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdContext.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdComponent.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdGlobal.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/ct4laz/pl_components/pl_lockbox/lib/x86_64-linux/qt5/lbbigint.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/ct4laz/pl_components/pl_lockbox/lib/x86_64-linux/qt5/lbasym.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/ct4laz/pl_components/pl_lockbox/lib/x86_64-linux/qt5/lbcipher.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/ct4laz/pl_components/pl_lockbox/lib/x86_64-linux/qt5/lbconst.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/ct4laz/pl_components/pl_lockbox/lib/x86_64-linux/qt5/lbrandom.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/ct4laz/pl_components/pl_lockbox/lib/x86_64-linux/qt5/lbutils.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/ct4laz/pl_components/pl_lockbox/lib/x86_64-linux/qt5/lbproc.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/ct4laz/pl_components/pl_lockbox/lib/x86_64-linux/qt5/lbstring.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdExceptionCore.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdIOHandler.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdTCPConnection.o
/opt/lazarus/fpc/units/x86_64-linux/rtl-extra/sockets.o
/opt/lazarus/fpc/units/x86_64-linux/iconvenc/iconvenc.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdException.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdResourceStrings.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdStream.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdStreamVCL.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdStack.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdStackConsts.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdCTypes.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdStackUnix.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdStackBSDBase.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-net/netdb.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdResourceStringsUnix.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdAntiFreezeBase.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdBuffer.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdBaseComponent.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdIntercept.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdResourceStringsCore.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdIOHandlerSocket.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdIOHandlerStack.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdReply.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdSocketHandle.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdCustomTransparentProxy.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdSocks.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdAssignedNumbers.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdIPAddress.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdReplyRFC.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdCustomTCPServer.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdScheduler.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdSchedulerOfThread.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdServerIOHandler.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdServerIOHandlerStack.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdThread.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdYarn.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdTask.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdThreadSafe.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdServerIOHandlerSocket.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdGlobalCore.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdSchedulerOfThreadDefault.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/x86_64-linux/ZDataset.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/x86_64-linux/ZConnection.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-db/db.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdSSLOpenSSL.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdTime.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/x86_64-linux/ubarcodes.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/base64.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxmemds.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/x86_64-linux/ZAbstractRODataset.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/x86_64-linux/ZAbstractDataset.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/x86_64-linux/ZAbstractTable.o
/opt/lazarus/fpc/units/x86_64-linux/rtl-objpas/fmtbcd.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZSysUtils.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/x86_64-linux/ZAbstractConnection.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcIntfs.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/x86_64-linux/ZSqlStrings.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcCache.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcCachedResultSet.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZCompatibility.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZExpression.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZClasses.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/maskutils.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-db/dbconst.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZMessages.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZFastCode.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcDbLib.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcMySql.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcPostgreSql.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcInterbase6.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcSqLite.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcOracle.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcASA.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcPooled.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZURL.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcConnection.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcLogging.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/x86_64-linux/ZPlainDbLibDriver.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/x86_64-linux/ZPlainDbLibConstants.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZTokenizer.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/x86_64-linux/ZGenericSqlAnalyser.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/x86_64-linux/ZGenericSqlToken.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/x86_64-linux/ZPlainDriver.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZCollections.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZVariant.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/x86_64-linux/ZSelectSchema.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcUtils.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcResultSetMetadata.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZEncoding.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/x86_64-linux/ZPlainLoader.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcResultSet.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcMetadata.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcGenericResolver.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcDbLibStatement.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcDbLibMetadata.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/x86_64-linux/ZSybaseToken.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/x86_64-linux/ZSybaseAnalyser.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcStatement.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcDbLibUtils.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcDbLibResultSet.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/x86_64-linux/ZPlainMySqlDriver.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/x86_64-linux/ZPlainMySqlConstants.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcMySqlStatement.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/x86_64-linux/ZMySqlToken.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcMySqlUtils.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcMySqlMetadata.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/x86_64-linux/ZMySqlAnalyser.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcMySqlResultSet.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/x86_64-linux/ZPlainPostgreSqlDriver.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcPostgreSqlStatement.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcPostgreSqlUtils.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcPostgreSqlMetadata.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/x86_64-linux/ZPostgreSqlToken.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/x86_64-linux/ZPostgreSqlAnalyser.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcPostgreSqlResultSet.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/x86_64-linux/ZPlainFirebirdDriver.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/x86_64-linux/ZPlainFirebirdInterbaseConstants.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcInterbase6Utils.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcInterbase6ResultSet.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcInterbase6Statement.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcInterbase6Metadata.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/x86_64-linux/ZInterbaseToken.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/x86_64-linux/ZInterbaseAnalyser.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/x86_64-linux/ZPlainSqLiteDriver.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcSqLiteStatement.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/x86_64-linux/ZSqLiteToken.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcSqLiteUtils.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcSqLiteMetadata.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/x86_64-linux/ZSqLiteAnalyser.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcSqLiteResultSet.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZMatchPattern.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/x86_64-linux/ZPlainOracleDriver.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/x86_64-linux/ZPlainOracleConstants.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcOracleStatement.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcOracleUtils.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcOracleMetadata.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/x86_64-linux/ZOracleToken.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/x86_64-linux/ZOracleAnalyser.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcOracleResultSet.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/x86_64-linux/ZPlainASADriver.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/x86_64-linux/ZPlainASAConstants.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcASAMetadata.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcASAStatement.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcASAUtils.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/x86_64-linux/ZDbcASAResultSet.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/x86_64-linux/ZSequence.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/x86_64-linux/ZDatasetUtils.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/x86_64-linux/ZSqlProcessor.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZExprParser.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZExprToken.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZVariables.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZFunctions.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZFunctionsMath.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZFunctionsDateTime.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZFunctionsStrings.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZFunctionsConvert.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/x86_64-linux/ZFunctionsOther.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/x86_64-linux/ZStreamBlob.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/x86_64-linux/ZScriptParser.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/x86_64-linux/ZSqlUpdate.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdSSLOpenSSLHeaders.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdGlobalProtocols.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdSSL.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdFIPS.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdResourceStringsProtocols.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdResourceStringsOpenSSL.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdCharsets.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdURI.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdUriUtils.o
/opt/lazarus/ccr/indy/Lib/lib/x86_64-linux/IdResourceStringsUriUtils.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/zint.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/x86_64-linux/udrawers.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/lconvencoding.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/propedits.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_basic.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_helper.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_render.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_svg.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_code.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_code128.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_2of5.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_upcean.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_plessey.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_telepen.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_medical.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_postal.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_auspost.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_pdf417.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_datamatrix.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_qr.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_aztec.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_maxicode.o
/opt/lazarus/fpc/units/x86_64-linux/rtl/dos.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/codepagescommon.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/codepagesasian.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/editbtn.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/valedit.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/filectrl.o
/opt/lazarus/lazarus/components/lazcontrols/lib/x86_64-linux/qt5/checkboxthemed.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/stringhashlist.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/objinspstrconsts.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/propeditutils.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/frmselectprops.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/stringspropeditdlg.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/keyvalpropeditdlg.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/collectionpropeditform.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/filefilterpropeditor.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/pagespropeditdlg.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/idewindowintf.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/groupededit.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/calendarpopup.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/timepopup.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/shellctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/wsshellctrls.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/ideimagesintf.o
/opt/lazarus/lazarus/components/buildintf/units/x86_64-linux/ideoptionsintf.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/lazideintf.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lazhelphtml.o
/opt/lazarus/lazarus/components/buildintf/units/x86_64-linux/baseideintf.o
/opt/lazarus/lazarus/components/buildintf/units/x86_64-linux/compoptsintf.o
/opt/lazarus/lazarus/components/buildintf/units/x86_64-linux/projectintf.o
/opt/lazarus/lazarus/components/buildintf/units/x86_64-linux/ideexterntoolintf.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/ideopteditorintf.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/srceditorintf.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lazhelpintf.o
/opt/lazarus/lazarus/components/buildintf/units/x86_64-linux/macrointf.o
/opt/lazarus/lazarus/components/buildintf/units/x86_64-linux/macrodefintf.o
/opt/lazarus/lazarus/components/buildintf/units/x86_64-linux/newitemintf.o
/opt/lazarus/lazarus/components/buildintf/units/x86_64-linux/projpackintf.o
/opt/lazarus/lazarus/components/buildintf/units/x86_64-linux/buildstrconsts.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/editorsyntaxhighlighterdef.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/idecommands.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/texttools.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/formeditingintf.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/objectinspector.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/idedialogs.o
/opt/lazarus/lazarus/components/buildintf/units/x86_64-linux/lazmsgworker.o
/opt/lazarus/lazarus/components/lazutils/lib/x86_64-linux/compwriterpas.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/componenteditors.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/unitresources.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/lazstringgridedit.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/checklistboxeditordlg.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/checkgroupeditordlg.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/componentreg.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/arrow.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/industrialbase.o
/opt/lazarus/lazarus/components/lazcontrols/lib/x86_64-linux/qt5/treefilteredit.o
/opt/lazarus/lazarus/components/lazcontrols/lib/x86_64-linux/qt5/listfilteredit.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/idehelpintf.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/componenttreeview.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/oifavoriteproperties.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/changeparentdlg.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/lclmemmanager.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_common.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_gs1.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_reedsolomon.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/lazbarcodes/packages/lib/zint/x86_64-linux/lbc_sjis.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/ex_rx_datapacket.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-db/bufdataset_parser.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-db/dbf_prscore.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-db/dbf_prsdef.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-db/dbf_prssupp.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxtools/x86_64-linux/qt5/rxdconst.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdbutils.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-registry/registry.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-base/inifiles.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-registry/xmlreg.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-xml/dom.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-xml/xmlread.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-xml/xmlwrite.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-xml/xmlutils.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-xml/dtdmodel.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-xml/xmlreader.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-xml/xmltextreader.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxlclutils.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxapputils.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxtools/x86_64-linux/qt5/rxstrutils.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxtools/x86_64-linux/qt5/rxdateutil.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxtools/x86_64-linux/qt5/rxlogging.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxtools/x86_64-linux/qt5/rxconst.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/registerrx.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/registerrxdb.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/registerrxtools.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxhistorynavigator.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxaboutdialog.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxaboutformunit.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxclock.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxcloseformvalidator.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxautopanel.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxboxprocs.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxctrls.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxcurredit.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdaterangeeditunit.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxversinfo.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxviewspanel.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/ex_rx_bin_datapacket.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/ex_rx_xml_datapacket.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdbcolorbox.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdbcomb.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdbctrls.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdbcurredit.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdbdateedit.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdbgrid.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdbgrid_columsunit.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdbgrid_findunit.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/exsortmds.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdbgridexportpdf.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdbgridexportpdfsetupunit.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdbgridfootertools.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdbgridfootertools_setup.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdbspinedit.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdbtimeedit.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxfilterby.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxlookup.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxpopupunit.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxseldsfrm.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxsortby.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxsortmemds.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdice.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxduallist.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxfduallst.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxfolderlister.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxhistory.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxinipropstorage.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxlclconst.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxlogin.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxmdi.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxpagemngr.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxpickdate.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxshortcutunit.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxspin.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxswitch.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxsystemservices.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxtbrsetup.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxtimeedit.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxtoolbar.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxtooledit.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdbgrid_popupfilterunit.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxdbverticalgrid.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxrangesel.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxxmlpropstorage.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxcontrols/x86_64-linux/qt5/rxpopupnotifier.o
/opt/lazarus/lazarus/packager/units/x86_64-linux/lazaruspackageintf.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/dbpropedits.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/dbctrls.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/dbgrids.o
/opt/lazarus/lazarus/components/ideintf/units/x86_64-linux/qt5/dbgridcolumnspropeditform.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/versionresource.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/resource.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/versiontypes.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/resdatastream.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/resourcetree.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/resmerger.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/resfactory.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/stringtableresource.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/groupiconresource.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/groupcursorresource.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/groupresource.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/icocurtypes.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/resreader.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/elfreader.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/elfconsts.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/elftypes.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/strtable.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-res/fpcrestypes.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxtools/x86_64-linux/qt5/rxutils.o
/opt/lazarus/lazarus/components/lazcontrols/lib/x86_64-linux/qt5/dividerbevel.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/colorbox.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-pdf/fppdf.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-pdf/fpparsettf.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-pdf/fpttf.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-pdf/fpttfsubsetter.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-pdf/fpfonttextmapping.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-pdf/fpttfencodings.o
/opt/lazarus/fpc/units/x86_64-linux/hash/md5.o
/opt/lazarus/config_lazarus/onlinepackagemanager/packages/Rx/lib/rxtools/x86_64-linux/qt5/rxtextholder.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/inipropstorage.o
/opt/lazarus/lazarus/lcl/units/x86_64-linux/xmlpropstorage.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-xml/xmlconf.o
/opt/lazarus/fpc/units/x86_64-linux/fcl-db/memds.o
)
INPUT(
-ldl
-lQt5Pas
-lX11
-lrt
)
GROUP(
-lc
)
INPUT(
/usr/lib/gcc/x86_64-linux-gnu/10/crtendS.o
/usr/lib/x86_64-linux-gnu/crtn.o
)
SECTIONS
{
  .fpcdata           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
  .threadvar : { *(.threadvar .threadvar.* .gnu.linkonce.tv.*) }
}
INSERT AFTER .data;
